import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AppProvider from "../contexts/AppProvider";
import Header from "@/components/layout/Header";
import { Providers } from "./providers";
import ThemeToggle from "@/components/ui/ThemeMode";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`} suppressHydrationWarning>
      <body>
        <Providers>
          <Header />
          <main
            className="mt-18 bg-white dark:bg-gray-900"
          >
            <AppProvider>
              {children}
            </AppProvider>
            <div      
              className="fixed bottom-8 right-8 z-10"
            >
              <ThemeToggle />
            </div>
          </main>
        </Providers>
      </body>
    </html>
  );
}
